add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"
#vicmd_symbol = "[](bold green) "


[kubernetes]
disabled = false

[git_metrics]
disabled = false

[git_status]
up_to_date = "✓"

